name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Test live install script
      run: |
        # Test the actual install script from GitHub Pages
        curl -LsSf https://iantimmis.github.io/fclip/install.sh | sh
        
        # Verify installation
        test -f ~/.local/bin/fclip && echo "✅ fclip installed"
        test -f ~/.local/bin/fcopy && echo "✅ fcopy installed"
        test -f ~/.local/bin/fpaste && echo "✅ fpaste installed" 
        test -f ~/.local/bin/fcut && echo "✅ fcut installed"
        test -f ~/.local/bin/fstatus && echo "✅ fstatus installed"
        test -f ~/.local/bin/fclear && echo "✅ fclear installed"
        
        # Test that commands work
        fclip --version
        echo "✅ Live install script works perfectly!"
    
    - name: Run tests
      run: |
        chmod +x test/test.sh
        ./test/test.sh
    
    - name: Test installer script
      run: |
        # Test that installer script is valid bash
        bash -n docs/install.sh
        echo "✅ Installer script syntax is valid"
    
    - name: Test fclip commands directly
      run: |
        # Quick smoke test of each command
        echo "test content" > test_smoke.txt
        ./src/fcopy test_smoke.txt
        ./src/fstatus
        rm test_smoke.txt  # Remove so paste can work
        ./src/fpaste
        ./src/fclear
        ./src/fclip --version
        ./src/fclip --help
        echo "✅ All commands executed without errors"
