name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install fclip locally
      run: |
        mkdir -p ~/.local/bin
        chmod +x src/*
        cp src/* ~/.local/bin/
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    
    - name: Run tests
      run: |
        chmod +x test/test.sh
        ./test/test.sh
    
    - name: Test installer script
      run: |
        # Test that installer script is valid bash
        bash -n docs/install.sh
        echo "✅ Installer script syntax is valid"
    
    - name: Test fclip commands directly
      run: |
        # Quick smoke test of each command
        echo "test content" > test_smoke.txt
        ./src/fcopy test_smoke.txt
        ./src/fstatus
        ./src/fpaste
        ./src/fclear
        ./src/fclip --version
        ./src/fclip --help
        echo "✅ All commands executed without errors"
